# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Forlogin',
            },
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-time']},
        ),
    ]
